defaults:
  - defaults
  - _self_

experiment:
  name: "phase_classification_v1"
  seed: 42
  seeds: [42, 123, 456]

  # Data Paths
  train_csv: "data_preprocessing/data/深医_final_data.csv"
  external_csv: "data_preprocessing/data/福鼎_final_data.csv"
  
  # Output
  save_dir: "./runs/${now:%Y-%m-%d}/${now:%H-%M-%S}"
  
  # Global switches
  use_gpu: true
  debug: false

hydra:
  run:
    dir: ${experiment.save_dir}
